name: Gitea Actions Demo
run-name: Build-Test bannertool
on: [push]

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          apt update -y
          apt install build-essential cmake -y
          cmake -B cmake-build-debug
          cmake --build cmake-build-debug
      - name: upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: bannertool
          path: cmake-build-debug/bannertool